### ISSUE TITLE
Calls to get GetFeatures and FeatureEnabled fail due to marshall failures

### ISSUE THREAD

**Issue by lwaddicor** [BulletTrainHQ/bullet-train-go-client#1]
When making calls to the api I get failures in unmarshalling

```
import (
	"fmt"
	bullettrain "github.com/BulletTrainHQ/bullet-train-go-client"
)

func main() {

	bt := bullettrain.DefaultClient("<my_api_key>")
	f, err := bt.GetFeatures()
	if err != nil {
		fmt.Printf("error: %+v\n", err)
		return
	}
	fmt.Printf("%+v\n", f)
}
```

Results in 
```
error: json: cannot unmarshal number into Go struct field Flag.feature_state_value of type string
```

My project has 3 features,
```
'stats_max_parallel' remote config, value 200
'stats_max_parallel_2' feature flag, value false
`stats_test' feature flag, value false
```

All default settings other than that

**Comment by dabeeeenster** [comment]
Hi - thanks for the bug report - we're looking into it!

**Comment by tzdybal** [comment]
Before we fix this, you can do following workaround:
1. Edit your remote config (`stats_max_parallel`) by adding `.` on the end - this way it will be a string, not integer.
2. In your Go code you can use `fmt.Sscanf` for parsing as int. (Or you can remove the trailing dot and use `strconv.ParseInt`).

Not pretty, but should work.

**Comment by lwaddicor** [comment]
Thanks, did a little workaround in your library with an unmarshaller that can handle string or int64's

I'll push a pr this evening so you can have a look. Depends on whether the output of the service is intended to be heterogeneous or not i guess :D

**Comment by dabeeeenster** [comment]
Great thanks so much @lwaddicor

**Comment by lwaddicor** [comment]
I see this has already been fixed in https://github.com/BulletTrainHQ/bullet-train-go-client/commit/09de7150e895e5489d3738a732a8b480a073818c

Thanks, I'll close this now

**Comment by tzdybal** [comment]
@lwaddicor I didn't see your comment before committing my changes.
Hope the updated version works for you!

**Comment by lwaddicor** [comment]
Yeah works great!
